model:
  name: test
  attributes:
    - name: name
      type: string
      required: false
routes:
  - path: /hello
    children:
      - method: GET
        path: ""
        handler: Find
      - method: POST
        path: ""
        handler: Insert
